# user in container
ARG CONTAINER_USER=user
ARG CONTAINER_GROUP=user

ARG CONTAINER_USER_ID=1000
ARG CONTAINER_GROUP_ID=1000

# set location of workspace directory
# (temporary space within container image)
ARG WORKSPACE_ROOT_DIR="/home/${CONTAINER_USER}"

# Alpine release and options
ARG ALPINE_RELEASE=3.24-alpine3.24-dev

# ansible CLI tools versions
ARG ANSIBLE_CLI_VERSION=v2.21.1

# cert-manager CLI version
ARG CM_CTL_CLI_VERSION=v2.5.0

# Helm version
ARG HELM_CLI_VERSION=v4.2.2

# kubectl version
ARG K9S_CLI_VERSION=v0.51.0

# kops version
ARG KOPS_CLI_VERSION=v1.36.0-beta.1

# kubectl version
ARG KUBECTL_CLI_VERSION=v1.36.2

# Kustomize version
ARG KUSTOMIZE_CLI_VERSION=5.8.1

# OpenTofu version
ARG OPENTOFU_CLI_VERSION=1.12.5

# OVHcloud CLI version (https://github.com/ovh/ovhcloud-cli)
ARG OVHCLOUD_CLI_VERSION=v0.12.0

# SwarmCLI version
ARG SWARM_CLI_VERSION=v1.12.0

# Terraform version
ARG TERRAFORM_CLI_VERSION=1.16.0-alpha20260617

# Terragrunt version
ARG TERRAGRUNT_CLI_VERSION=v1.1.0-rc2

# container as builder for preparing OVH cloud tools
FROM dhi.io/alpine-base:${ALPINE_RELEASE} AS ovh-tools-builder

LABEL stage="ovh-tools-builder" \
      description="Alpine-based container builder for preparing OVH cloud tools" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tools" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# install required packages and additional applications
RUN apk add --no-cache ca-certificates binutils curl unzip

# container as builder for preparing OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-ansible-cli-builder

LABEL stage="ovh-tools-ansible-cli-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool ansible" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool ansible" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG ANSIBLE_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download and install ansible tool
RUN apk add --no-cache python3 py3-pip
RUN python3 -m pip install --break-system-packages "https://github.com/ansible/ansible/archive/refs/tags/${ANSIBLE_CLI_VERSION}.tar.gz"


# container as builder for preparing OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-cm-builder

LABEL stage="ovh-tools-cm-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool cert-manager CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool cert-manager CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG CM_CTL_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download cert-manager
ADD "https://github.com/cert-manager/cmctl/releases/download/${CM_CTL_CLI_VERSION}/cmctl_linux_${TARGETARCH}" "${WORKSPACE_ROOT_DIR}/cmctl_linux_${TARGETARCH}"

# install cert-manager
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/cmctl_linux_${TARGETARCH}" "/usr/local/bin/kubectl-cert_manager"


# container as builder for preparing OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-cnpg-builder

LABEL stage="ovh-tools-cnpg-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool CNPG CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool CNPG CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# install kubectl CNPG plugin
RUN mkdir -p "/usr/local/bin/" && \
    curl -sSfL https://github.com/cloudnative-pg/cloudnative-pg/raw/main/hack/install-cnpg-plugin.sh | \
    sh -s -- -b /usr/local/bin


# container as builder for preparing OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-helm-builder

LABEL stage="ovh-tools-helm-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool HELM CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool HELM CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG HELM_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download HELM archive file
ADD "https://get.helm.sh/helm-${HELM_CLI_VERSION}-${TARGETOS}-${TARGETARCH}.tar.gz" "${WORKSPACE_ROOT_DIR}/"

# install HELM
RUN mkdir -p "/usr/local/bin/" && tar -xvf "${WORKSPACE_ROOT_DIR}/helm-${HELM_CLI_VERSION}-${TARGETOS}-${TARGETARCH}.tar.gz" -C "/usr/local/bin" --strip-components 1 --no-anchored "helm"


# container as builder for preparing OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-k9s-builder

LABEL stage="ovh-tools-k9s-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool k9s CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool k9s CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG K9S_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download k9s CLI binary file
ADD "https://github.com/derailed/k9s/releases/download/${K9S_CLI_VERSION}/k9s_${TARGETOS}_${TARGETARCH}.tar.gz" "${WORKSPACE_ROOT_DIR}/"

# install k9s
RUN mkdir -p "/usr/local/bin/" && tar -xvf "${WORKSPACE_ROOT_DIR}/k9s_${TARGETOS}_${TARGETARCH}.tar.gz" -C "/usr/local/bin" --no-anchored "k9s"


# container as builder for preparing kops OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-kops-builder

LABEL stage="ovh-tools-kops-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool kops CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool kops CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG KOPS_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download kubectl CLI binary file
ADD "https://github.com/kubernetes/kops/releases/download/${KOPS_CLI_VERSION}/kops-${TARGETOS}-${TARGETARCH}" "${WORKSPACE_ROOT_DIR}/"

# install kubectl
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/kops-${TARGETOS}-${TARGETARCH}" "/usr/local/bin/kops"


# container as builder for preparing OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-kubectl-builder

LABEL stage="ovh-tools-kubectl-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool kubectl CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool kubectl CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG KUBECTL_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download kubectl CLI binary file
ADD "https://dl.k8s.io/release/${KUBECTL_CLI_VERSION}/bin/linux/${TARGETARCH}/kubectl" "${WORKSPACE_ROOT_DIR}/"

# install kubectl
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/kubectl" "/usr/local/bin/"


# container as builder for preparing OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-kustomize-builder

LABEL stage="ovh-tools-kustomize-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool kustomize CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool kustomize CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG KUSTOMIZE_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download kustomize archive
ADD "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE_CLI_VERSION}/kustomize_v${KUSTOMIZE_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.tar.gz" "${WORKSPACE_ROOT_DIR}/"

# install kustomize
RUN mkdir -p "/usr/local/bin/" && tar -xvf "${WORKSPACE_ROOT_DIR}/kustomize_v${KUSTOMIZE_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.tar.gz" -C "/usr/local/bin" --no-anchored "kustomize"


# container as builder for preparing OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-opentofu-builder

LABEL stage="ovh-tools-opentofu-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool OpenTofu CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool OpenTofu CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG OPENTOFU_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download OpenTofu CLI archive file
ADD "https://github.com/opentofu/opentofu/releases/download/v${OPENTOFU_CLI_VERSION}/tofu_${OPENTOFU_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.zip" "${WORKSPACE_ROOT_DIR}/"

# install OpenTofu CLI binary
RUN mkdir -p "/usr/local/bin/" && unzip "tofu_${OPENTOFU_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.zip" -d "/usr/local/bin/"


# container as builder for preparing OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-ovhcloud-cli-builder

LABEL stage="ovh-tools-ovhcloud-cli-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool OVHcloud CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool OVHcloud CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG OVHCLOUD_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

RUN case "${TARGETARCH}" in \
      amd64) OVHCLOUD_CLI_ARCH=x86_64 ;; \
      arm64) OVHCLOUD_CLI_ARCH=arm64 ;; \
      386) OVHCLOUD_CLI_ARCH=i386 ;; \
      *) echo "unsupported TARGETARCH: ${TARGETARCH}" >&2; exit 1 ;; \
    esac && \
    mkdir -p "/usr/local/bin/" && \
    curl -fsSL -o "${WORKSPACE_ROOT_DIR}/ovhcloud-cli.tar.gz" \
      "https://github.com/ovh/ovhcloud-cli/releases/download/${OVHCLOUD_CLI_VERSION}/ovhcloud-cli_${TARGETOS}_${OVHCLOUD_CLI_ARCH}.tar.gz" && \
    tar -xvf "${WORKSPACE_ROOT_DIR}/ovhcloud-cli.tar.gz" -C "/usr/local/bin" --no-anchored "ovhcloud" && \
    rm -f "${WORKSPACE_ROOT_DIR}/ovhcloud-cli.tar.gz"


# container as builder for preparing OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-swarmcli-builder

LABEL stage="ovh-tools-swarmcli-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool SwarmCLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool SwarmCLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG SWARM_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# install SwarmCLI
RUN mkdir -p "/usr/local/bin/" && \
    curl -fsSL https://swarmcli.io/install.sh | \
    sh -s -- ce /usr/local/bin "${SWARM_CLI_VERSION}"


# container as builder for preparing OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-terraform-builder

LABEL stage="ovh-tools-terraform-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool terraform" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool terraform" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG TERRAFORM_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download TF CLI archive file
ADD "https://releases.hashicorp.com/terraform/${TERRAFORM_CLI_VERSION}/terraform_${TERRAFORM_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.zip" "${WORKSPACE_ROOT_DIR}/"

# install TF CLI binary
RUN mkdir -p "/usr/local/bin/" && unzip "terraform_${TERRAFORM_CLI_VERSION}_${TARGETOS}_${TARGETARCH}.zip" -d "/usr/local/bin/"


# container as builder for preparing OVH cloud tools
FROM ovh-tools-builder AS ovh-tools-terragrunt-builder

LABEL stage="ovh-tools-terragrunt-builder" \
      description="Alpine-based container builder for preparing OVH cloud tool terragrunt CLI" \
      org.opencontainers.image.description="Alpine-based container builder for preparing OVH cloud tool terragrunt CLI" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH
ARG TERRAGRUNT_CLI_VERSION

ARG WORKSPACE_ROOT_DIR
WORKDIR "${WORKSPACE_ROOT_DIR}"

# download kubectl CLI binary file
ADD "https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_CLI_VERSION}/terragrunt_${TARGETOS}_${TARGETARCH}" "${WORKSPACE_ROOT_DIR}/"

# install terragrunt CLI
RUN mkdir -p "/usr/local/bin/" && install -v -o root -g root -m 0755 "${WORKSPACE_ROOT_DIR}/terragrunt_${TARGETOS}_${TARGETARCH}" "/usr/local/bin/terragrunt"


FROM scratch AS ovh-tools-binaries-aggregator

# transfer tools from builders
COPY --from=ovh-tools-ansible-cli-builder "/usr/local/bin" "/usr/local/bin"
COPY --from=ovh-tools-ansible-cli-builder "/usr/local/lib/" "/usr/local/lib"
COPY --from=ovh-tools-cm-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=ovh-tools-cnpg-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=ovh-tools-helm-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=ovh-tools-k9s-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=ovh-tools-kops-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=ovh-tools-kubectl-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=ovh-tools-kustomize-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=ovh-tools-opentofu-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=ovh-tools-ovhcloud-cli-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=ovh-tools-swarmcli-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=ovh-tools-terraform-builder "/usr/local/bin/" "/usr/local/bin/"
COPY --from=ovh-tools-terragrunt-builder "/usr/local/bin/" "/usr/local/bin/"


# container as final image for providing OVH cloud tools
FROM dhi.io/alpine-base:${ALPINE_RELEASE} AS ovh-tools-image

LABEL stage="ovh-tools-image" \
      description="Alpine-based container with OVH cloud tools" \
      org.opencontainers.image.description="Alpine-based container with OVH cloud tools" \
      org.opencontainers.image.url=https://github.com/stefanbosak/ovh-cloud-tools \
      org.opencontainers.image.source=https://github.com/stefanbosak/ovh-cloud-tools

ARG TARGETOS
ARG TARGETARCH

# user in container
ARG CONTAINER_USER
ARG CONTAINER_GROUP

ARG CONTAINER_USER_ID
ARG CONTAINER_GROUP_ID

ARG HOME_ROOT_DIR="/home/${CONTAINER_USER}"

WORKDIR "${HOME_ROOT_DIR}"

RUN mkdir -p "/usr/local/bin/" && \
    apk add --no-cache \
      bash \
      bash-completion \
      bc \
      bind-tools \
      ca-certificates \
      curl \
      git \
      gnupg \
      gzip \
      iproute2 \
      iputils-ping \
      jq \
      kmod \
      lsof \
      openssh-client-default \
      pigz \
      procps-ng \
      psmisc \
      py3-argcomplete \
      python3 \
      ripgrep \
      rsync \
      shadow \
      socat \
      unzip \
      wget \
      whois && \
    ln -sf /usr/bin/python3 /usr/bin/python

# copy tools from aggregator
COPY --from=ovh-tools-binaries-aggregator / /

# setup user and group
RUN if getent group "${CONTAINER_GROUP_ID}" > /dev/null; then \
      _existing_group="$(getent group "${CONTAINER_GROUP_ID}" | cut -d: -f1)"; \
      if [ "${_existing_group}" != "${CONTAINER_GROUP}" ]; then \
        groupmod -n "${CONTAINER_GROUP}" "${_existing_group}"; \
      fi; \
    else \
      groupadd --gid "${CONTAINER_GROUP_ID}" "${CONTAINER_GROUP}"; \
    fi \
    && if getent passwd "${CONTAINER_USER_ID}" > /dev/null; then \
         _existing_user="$(getent passwd "${CONTAINER_USER_ID}" | cut -d: -f1)"; \
         if [ "${_existing_user}" != "${CONTAINER_USER}" ]; then \
           if [ -d "/home/${_existing_user}" ]; then \
             mv "/home/${_existing_user}" "/home/${CONTAINER_USER}"; \
           fi; \
           usermod -d "${HOME_ROOT_DIR}" -l "${CONTAINER_USER}" "${_existing_user}"; \
         fi; \
       else \
         useradd \
           --uid "${CONTAINER_USER_ID}" \
           --gid "${CONTAINER_GROUP_ID}" \
           -M -d "${HOME_ROOT_DIR}" \
           -s /bin/bash \
           "${CONTAINER_USER}"; \
       fi \
    && chown -R "${CONTAINER_USER}:${CONTAINER_GROUP}" "${HOME_ROOT_DIR}" && \
# enable tools completions (required to run given tool to generate completion file content)
    ln -s /usr/local/bin/kubectl-cert_manager /usr/local/bin/cmctl && \
    cmctl completion bash > /usr/share/bash-completion/completions/cmctl && \
    ln -s /usr/local/bin/kubectl-cnpg /usr/local/bin/cnpgctl && \
    cnpgctl completion bash > /usr/share/bash-completion/completions/cnpgctl && \
    sed -i 's/kubectl-cnpg/cnpgctl/g' /usr/share/bash-completion/completions/cnpgctl && \
    helm completion bash > "/usr/share/bash-completion/completions/helm" && \
    k9s completion bash > "/usr/share/bash-completion/completions/k9s" && \
    kops completion bash > "/usr/share/bash-completion/completions/kops" && \
    kubectl completion bash > "/usr/share/bash-completion/completions/kubectl" && \
    cp "/usr/share/bash-completion/completions/kubectl" "/usr/share/bash-completion/completions/k" && \
    sed -i 's/kubectl/k/g' "/usr/share/bash-completion/completions/k" && \
    ln -s /usr/local/bin/kubectl /usr/local/bin/k && \
    kustomize completion bash > "/usr/share/bash-completion/completions/kustomize" && \
    ovhcloud completion bash > /usr/share/bash-completion/completions/ovhcloud && \
    echo "complete -C terraform terraform" > "/usr/share/bash-completion/completions/terraform" && \
    echo "complete -C terragrunt terragrunt" > "/usr/share/bash-completion/completions/terragrunt" && \
    echo "complete -C tofu tofu" > "/usr/share/bash-completion/completions/tofu" && \
    activate-global-python-argcomplete

# container user and group
USER "${CONTAINER_USER}:${CONTAINER_GROUP}"

WORKDIR "${HOME_ROOT_DIR}"

RUN cp /etc/skel/.bashrc /etc/skel/.profile "${HOME_ROOT_DIR}"

# open shell
CMD ["bash"]
